package com.example.shoppingCart.StockModels;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Embeddable
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Stock {

    @AllArgsConstructor
    public enum TypeEnum {
        STOCK("stock");
        private final String value;
    }

    private TypeEnum type;

    @ApiModelProperty("A unique stock identifier auto generated by the system")
    @Column(name = "STOCK_ID")
    @Id
    private String id;

    @Embedded
    private StockInfo attributes;

    public Stock(StockInfo attributes) {
        this.attributes = attributes;
    }
}

